#                            -*- mode: org; -*-
#
#+TITLE:                README for OpenFOAM-3.0.1
#+AUTHOR:               The OpenFOAM Foundation
#+DATE:                     15th December 2015
#+LINK:                  http://www.openfoam.org
#+OPTIONS: author:nil ^:{}
# Copyright (c) 2015 OpenFOAM Foundation.

* Attention: Resolving CGAL and Build Issues

** Install (part of) Required Dependencies
Ensure all necessary development libraries are installed:

#+BEGIN_SRC bash
sudo apt install libgmp-dev libmpfr-dev libeigen3-dev libboost-dev flex libscotch-dev libscotchmetis-dev libcgal-dev
#+END_SRC

** Handle Flex Version Compatibility (for versions > 2.6.x)
If using a newer version of =flex=, patch the lexer files to handle version checks:

#+BEGIN_SRC bash
# Check flex version
flex --version

# Patch affected files
find src applications -name "*.L" -type f | xargs sed -i -e 's=$$YY_FLEX_SUBMINOR_VERSION$$=YY_FLEX_MINOR_VERSION < 6 \&\& $$1]='
#+END_SRC

** Note on =-lCGAL= Linker Flag (CGAL >= 5.0)
Since CGAL version 5.0, the library is header-only by default.
- You no longer need to compile or link against =libCGAL.so=.
- The =-lCGAL= linker flag is **not required** in =./wmake/rules/General/CGAL=.
- Simply include CGAL headers in your code; all functionality is instantiated at compile time.

** Handling "foamy*Mesh" Compilation Errors
The =foamy*Mesh= applications are rarely used and may fail to build due to outdated dependencies or compatibility issues.

To skip these without stopping the entire build:
#+BEGIN_SRC bash
./Allwmake -k
#+END_SRC
The =-k= (or =--keep-going=) option tells =make= to continue building other targets even after errors.

* About OpenFOAM
  OpenFOAM is a free, open source computational fluid dynamics (CFD) software
  package released by the OpenFOAM Foundation. It has a large user base across
  most areas of engineering and science, from both commercial and academic
  organisations. OpenFOAM has an extensive range of features to solve anything
  from complex fluid flows involving chemical reactions, turbulence and heat
  transfer, to solid dynamics and electromagnetics.

* Copyright
  OpenFOAM is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  See the file =COPYING= in this directory or
  [[http://www.gnu.org/licenses/]], for a description of the GNU General Public
  License terms under which you can copy the files.

* [[http://www.OpenFOAM.org/git.php][Download and installation instructions]]
* [[http://www.OpenFOAM.org/docs][Documentation]]
* [[http://www.OpenFOAM.org/bugs][Reporting bugs in OpenFOAM]]
* [[http://www.openfoam.org/contact][Contacting the OpenFOAM Foundation]]
